openapi: 3.0.0
info:
  version: 1.0.0
  title: FOSS Foundation metadata schema
  description: Fields describing a FOSS foundation for https://fossfoundation.info/data
paths: {}
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ShaneCurcuru/foundation-schema/1.0.0
components:
  schemas:
    Foundation:
      type: object
      title: FOSS Foundation metadata schema
      required:
        - identifier
        - commonName
        - legalName
        - website
        - addressCountry
        - nonprofitStatus
      properties:
        identifier:
          title: Used as filename base or fragment reference within FOSSFoundation.info.
          description: Shortest unique and human-recognizable reference to org; lowercased; used for lookups.
          type: string
          pattern: "^[a-z][a-z]*$"
        commonName:
          title: Common Name
          description: Commonly used name in public.
          type: string
        legalName:
          title: Legal Name
          description: The official name of the organization, e.g. the registered company name.
          type: string
        description:
          title: Description
          description: One sentence brief overview of organization.
          type: string
        website:
          title: Website
          description: Primary website homepage that users would look for.
          type: string
          format: uri
        foundingDate:
          title: Founding Date
          description: The date that this organization was legally founded.
          type: string
          format: date
        dissolutionDate:
          title: Dissolution Date
          description: The date that this organization was legally dissolved (if applicable).
          type: string
          format: date
        addressCountry:
          title: Location
          description: Country organization is incorporated in; ISO 3166-1 alpha-2.
          type: string
          pattern: "^[A-Z][A-Z]$"
        addressRegion:
          title: State
          description: >-
            State, Province, District, or similar region organization is incorporated in.
          type: string
        newProjects:
          title: Accepts new projects?
          description: Does this organization actively accept new projects for hosting?
          type: string
        softwareType:
          title: Software Types
          description: What general kind of software does this org create? May be 'various'.
          type: string
        wikidataId:
          title: Wikidata ID
          description: Wikidata ID for lookups.
          type: string
          pattern: '^Q[1-9]\d*$'
        boardSize:
          title: Board Size
          description: Number of board of director seats.
          type: number
        boardType:
          title: Board Type
          description: >-
            Approximate type of board: (non-paid) member elected; (paid) sponsor elected; appointed; self-perpetuating; etc.
          type: string
        boardurl:
          title: Board Website
          description: Official board information URL, typically with a list of directors.
          type: string
          format: url
        bylawsurl:
          title: Bylaws Website
          description: Corporate bylaws URL.
          type: string
          format: url
        numberOfEmployees:
          title: Approx Number Of Paid Staff
          description: Approximate number of paid employees or equivalents.
          type: number
        governanceOrg:
          title: Governance Description
          description: Brief description of corporate or organizational governance.
          type: string
        governanceTech:
          title: Project Governance Description
          description: Brief description of project-level technical governance.
          type: string
        projectsNotable:
          title: Example Projects Hosted
          description: Example list of highly notable software products.
          type: string
        projectsList:
          title: Project List Website
          description: Official URL listing of all sub-projects hosted.
          type: string
          format: url
        projectsServices:
          title: Services Provided
          description: Brief description of services offered to hosted projects.
          type: string
        fiscalHost: 
          title: Fiscal Host Type
          description: "If a fiscal host, enter the type of services provided: direct funding, indirect funding, employee services, etc."
          type: string
        nonprofitStatus:
          title: Nonprofit Type
          description: "Specific type of non-profit; types: https://schema.org/NonprofitType"
          type: string
        taxID:
          title: Tax Authority ID
          description: US IRS EIN/TIN, or other country's tax identifier (if any).
          type: string
        taxIDLocal:
          title: Local Tax Authority ID
          description: Per-state, province, district, or similar tax identifier (if any).
          type: string
        uniqueEntityID:
          title: Unique Entity ID
          description: US Government UEI string used for grants or contracts.
          type: string
        budgetUsd:
          title: Budget in USD
          description: Approximate annual budget in USD; estimate.
          type: string
        budgetYear:
          title: Budget Year
          description: Fiscal year budgetUsd number was entered for.
          type: string
        budgeturl:
          title: Budget Website
          description: Official budget or other financial information URL.
          type: string
          format: url
        budgetTransparent:
          title: Budget Transparency
          description: Is the official budget shared publicly and fully on a regular schedule?
          type: string
        funding:
          title: Funding Sources
          description: >-
            Primary funding sources in rough order: (corporate) sponsors; (individual) donations; grants; other.
          type: string
        sponsorurl:
          title: Sponsor List Website
          description: Official listing of sponsors from a published sponsorship program URL.
          type: string
          format: url
        sponsorList:
          title: Example Sponsors
          description: Example listing of top-level annual recurring sponsors from the most recent year.
          type: string
        sponsorships:
          title: Sponsorship Program Model
          description: >-
            Filename base(s) of mappings defining sponsorship levels, listings, etc.; see sponsorships-schema.json
          type: array
          items:
            type: string
          uniqueItems: true
        licenses:
          title: Licenses Used
          description: Licenses used on software provided if there is a policy; SPDX Identifiers or 'various'.
          type: string
        claPolicy:
          title: CLA Policy
          description: >-
            Describe if the organization uses CLAs, DCOs, or other required incoming grants from contributors.
          type: string
        ethicsPolicy:
          title: Ethics/COI Policy
          description: Link to any primary ethics or COI policies posted.
          type: string
          format: url
        conducturl:
          title: Code Of Conduct Policy
          description: Link to official Code of Conduct.
          type: string
          format: url
        conductEvents:
          title: Event Code Of Conduct Policy
          description: Link to official event-related Code of Conduct.
          type: string
          format: url
        conductSource:
          title: Source Of Code Of Conduct
          description: Cited source or inspiration for Code of Conduct policy.
          type: string
        conductLinked:
          title: Where Code Of Conduct Linked
          description: Describe where the Code of Conduct is linked from the website - footer, header, navigation, none?
          type: string
        diversityPolicy:
          title: Diversity Policy Website
          description: Diversity, inclusion, or other related policies or informational page.
          type: string
          format: url
        diversityDescription:
          title: Description Of Diversity Policy
          description: Brief description of actual diversity, inclusion, or other related policies.
          type: string
        brandPrimary:
          title: Primary Brand Name
          description: What is the primary brand name/trademark of the organization?
          type: string
        brandSecondary:
          title: Secondary Brand Name(s)
          description: Example listing of any major secondary brand names/marks.
          type: string
        brandReg:
          title: Is Primary Brand Registered?
          description: >-
            Is the primary brand a registered trademark in at least one jurisdiction? (yes/no/or major countries registered in).
          type: string
        brandPolicy:
          title: Trademark Policy Website
          description: Link to official trademark usage policies.
          type: string
          format: url
        brandUse:
          title: Trademark Usage Website
          description: Link to official trademark FAQ or other policies.
          type: string
          format: url
        brandComments:
          title: Trademark Policy Description
          description: Brief description of trademark usage policies.
          type: string
        logo:
          title: Official Logo Link
          description: Official organizational logo URL; prefer SVG when available.
          type: string
          format: url
        logoReg:
          title: Is Logo Registered?
          description: >-
            Is the official logo a registered trademark? (yes/no/or major countries registered in).
          type: string
        subOrganization:
          title: Sub Entities Governed
          description: Identifier(s) of any sub-foundations tracked in _entities data.
          type: array
          items:
            type: string
            pattern: "^[a-z][a-z]*$"
          uniqueItems: true
