#!/usr/bin/env bash
# Build the default liquid template from the foundation schema.
set -euo pipefail
cd "$(dirname "$0")/../.."
echo "Building default liquid template from schema"
ruby assets/ruby/schema_utils.rb -i _data/foundations-schema.json -o _includes/foundation-fields.html -t _data/foundation-template.md
